In [1]:
import pandas as pd
from Bio import SeqIO
from collections import defaultdict
import statistics as st

In [18]:
# READ IN - Multiple sequence alignment
fasta="/Users/varadakhot/Library/CloudStorage/OneDrive-Friedrich-Schiller-UniversitätJena/MCP_struct/RF_models_automation/RF_results/foldmason/cluster_0_1_mixed_db_out/cluster_0_1_mixed_MSTA_aa_plus_ec6098ref_2.faa"

seq_dict = {} 
for record in SeqIO.parse(fasta, "fasta"):
    seq_dict[record.id.strip()]=record.seq
seq_dict
msa_df = pd.DataFrame.from_dict(seq_dict,orient='index')
msa_df = msa_df.loc[~msa_df.index.str.contains("EC6098") ]
# msa_df.to_csv("amino_acid_switching_R/msa_df.csv")

# READ IN - features
TOP = 200 # number of features to keep
feat_df = pd.read_csv("/Users/varadakhot/Library/CloudStorage/OneDrive-Friedrich-Schiller-UniversitätJena/MCP_struct/Microviridae_analysis/multiple_cluster_analysis/combined_model_phyloglm/phyloglm_intersect_giniscores_new.tsv",sep='\t')
feat_df
# Keep only features above a threshold
important = feat_df[feat_df.feature_importance_vals > 0.0001].copy()
print(important)

# READ IN - Labels
labels_df = pd.read_csv("/Users/varadakhot/Library/CloudStorage/OneDrive-Friedrich-Schiller-UniversitätJena/MCP_struct/RF_models_automation/RF_results/cluster_0_1_mixed_MSTA_aa_plus_ec6_data_df.tsv", sep='\t',usecols=["protein",'ecosystem_subtype'])
print(labels_df)
labels_df = labels_df.drop_duplicates('protein').set_index("protein")
labels_df

# join the biome labels to the multiple sequence alignment

msa_df_labelled = msa_df.join(labels_df, how="left")
msa_df_labelled.to_csv("msa_df_labelled.csv")

     Unnamed: 0 feature  Estimate        SE   z.value       p.value     alpha  \
0             0   445_F -2.323584  0.722366 -3.216630  1.297059e-03  0.468187
1             1   324_Q -2.301889  0.501361 -4.591284  4.405279e-06  0.576690
2             2   330_K -2.588086  0.476886 -5.427056  5.729117e-08  0.521602
3             3    19_M -2.569998  0.543479 -4.728792  2.258592e-06  0.614560
4             4   399_L -2.499384  0.591347 -4.226596  2.372527e-05  0.545660
..          ...     ...       ...       ...       ...           ...       ...
572         572   265_A -1.574068  0.414116 -3.801029  1.440963e-04  0.215822
573         573   534_N  2.654868  0.736825  3.603120  3.144197e-04  0.240998
574         574   257_G -1.053471  0.278274 -3.785734  1.532555e-04  0.210105
575         575   389_M -1.727666  0.485139 -3.561180  3.691921e-04  0.223072
576         576   518_N -2.020450  0.584409 -3.457256  5.457060e-04  0.213611

         padj  imp_order  feature_importance_vals  abs_z.value  abs_Estimate  \
0    0.009599          0                 0.011341     3.216630      2.323584
1    0.000100          2                 0.008046     4.591284      2.301889
2    0.000002          3                 0.007974     5.427056      2.588086
3    0.000055          4                 0.007836     4.728792      2.569998
4    0.000386          5                 0.007787     4.226596      2.499384
..        ...        ...                      ...          ...           ...
572  0.001668       1597                 0.000103     3.801029      1.574068
573  0.003069       1599                 0.000103     3.603120      2.654868
574  0.001744       1620                 0.000101     3.785734      1.053471
575  0.003511       1626                 0.000101     3.561180      1.727666
576  0.004872       1638                 0.000100     3.457256      2.020450

    biome_predictor
0              lake
1              lake
2              lake
3              lake
4              lake
..              ...
572            lake
573           ocean
574            lake
575            lake
576            lake

[577 rows x 13 columns]
                                                protein ecosystem_subtype
0     IMGVR_UViG_3300027969_000035|3300027969|Ga0209...              Lake
1     IMGVR_UViG_3300027969_000036|3300027969|Ga0209...              Lake
2     IMGVR_UViG_3300027973_000026|3300027973|Ga0209...              Lake
3     IMGVR_UViG_3300027974_000782|3300027974|Ga0209...              Lake
4     IMGVR_UViG_3300028553_000004|3300028553|Ga0247...              Lake
...                                                 ...               ...
1105                                   MGYP001269301632           Oceanic
1106                                   MGYP001445468529           Oceanic
1107                                   MGYP000515316755              Lake
1108                                   MGYP003325855982           Oceanic
1109                                   MGYP003333944615           Oceanic

[1110 rows x 2 columns]

In [19]:
important

,Unnamed: 0,feature,Estimate,SE,z.value,p.value,alpha,padj,imp_order,feature_importance_vals,abs_z.value,abs_Estimate,biome_predictor
0,0,445_F,-2.323584,0.722366,-3.216630,1.297059e-03,0.468187,0.009599,0,0.011341,3.216630,2.323584,lake
1,1,324_Q,-2.301889,0.501361,-4.591284,4.405279e-06,0.576690,0.000100,2,0.008046,4.591284,2.301889,lake
2,2,330_K,-2.588086,0.476886,-5.427056,5.729117e-08,0.521602,0.000002,3,0.007974,5.427056,2.588086,lake
3,3,19_M,-2.569998,0.543479,-4.728792,2.258592e-06,0.614560,0.000055,4,0.007836,4.728792,2.569998,lake
4,4,399_L,-2.499384,0.591347,-4.226596,2.372527e-05,0.545660,0.000386,5,0.007787,4.226596,2.499384,lake
...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,572,265_A,-1.574068,0.414116,-3.801029,1.440963e-04,0.215822,0.001668,1597,0.000103,3.801029,1.574068,lake
573,573,534_N,2.654868,0.736825,3.603120,3.144197e-04,0.240998,0.003069,1599,0.000103,3.603120,2.654868,ocean
574,574,257_G,-1.053471,0.278274,-3.785734,1.532555e-04,0.210105,0.001744,1620,0.000101,3.785734,1.053471,lake
575,575,389_M,-1.727666,0.485139,-3.561180,3.691921e-04,0.223072,0.003511,1626,0.000101,3.561180,1.727666,lake
576,576,518_N,-2.020450,0.584409,-3.457256,5.457060e-04,0.213611,0.004872,1638,0.000100,3.457256,2.020450,lake

In [20]:
top_feats_overall = important.sort_values('feature_importance_vals', ascending=False).head(n=TOP)
top_feats_overall

,Unnamed: 0,feature,Estimate,SE,z.value,p.value,alpha,padj,imp_order,feature_importance_vals,abs_z.value,abs_Estimate,biome_predictor
0,0,445_F,-2.323584,0.722366,-3.216630,1.297059e-03,0.468187,9.599039e-03,0,0.011341,3.216630,2.323584,lake
1,1,324_Q,-2.301889,0.501361,-4.591284,4.405279e-06,0.576690,1.002775e-04,2,0.008046,4.591284,2.301889,lake
2,2,330_K,-2.588086,0.476886,-5.427056,5.729117e-08,0.521602,2.219109e-06,3,0.007974,5.427056,2.588086,lake
3,3,19_M,-2.569998,0.543479,-4.728792,2.258592e-06,0.614560,5.542130e-05,4,0.007836,4.728792,2.569998,lake
4,4,399_L,-2.499384,0.591347,-4.226596,2.372527e-05,0.545660,3.863522e-04,5,0.007787,4.226596,2.499384,lake
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,410_V,-1.661102,0.274371,-6.054224,1.410965e-09,0.277722,8.688289e-08,218,0.000713,6.054224,1.661102,lake
196,196,65_A,-1.493190,0.252923,-5.903739,3.553552e-09,0.373833,1.855186e-07,219,0.000713,5.903739,1.493190,lake
197,197,50_C,-2.036071,0.341249,-5.966530,2.423526e-09,0.240225,1.337954e-07,220,0.000713,5.966530,2.036071,lake
198,198,209_D,1.453732,0.444673,3.269216,1.078460e-03,0.262089,8.221975e-03,222,0.000699,3.269216,1.453732,ocean
199,199,490_S,-2.051461,0.312287,-6.569149,5.060371e-11,0.242463,4.860992e-09,223,0.000697,6.569149,2.051461,lake

In [21]:
# split labeled msa_df into lake and ocean ones
lake_msa = msa_df_labelled.loc[msa_df_labelled['ecosystem_subtype'] == "Lake"]
ocean_msa = msa_df_labelled.loc[msa_df_labelled['ecosystem_subtype'] == "Oceanic"]

In [22]:
# map the individual msas into dictionaries
lake_msa_map_dict = {}
for column in lake_msa:
    if column not in ['ecosystem_subtype']:
        counts = lake_msa.groupby([column])[column].count().to_dict()
        lake_msa_map_dict[column] = counts
lake_msa_map_dict

ocean_msa_map_dict = {}
for column in ocean_msa:
    if column not in ['ecosystem_subtype']:
        counts = ocean_msa.groupby([column])[column].count().to_dict()
        ocean_msa_map_dict[column] = counts
ocean_msa_map_dict

{0: {'-': 148, 'D': 1, 'L': 13, 'M': 108, 'P': 9, 'T': 7},
 1: {'-': 143,
  'A': 15,
  'E': 2,
  'F': 2,
  'G': 11,
  'H': 3,
  'K': 2,
  'L': 1,
  'M': 5,
  'N': 3,
  'P': 3,
  'Q': 3,
  'S': 78,
  'T': 2,
  'V': 13},
 2: {'-': 132,
  'A': 9,
  'D': 6,
  'E': 1,
  'F': 1,
  'G': 11,
  'I': 55,
  'K': 8,
  'L': 11,
  'M': 21,
  'N': 7,
  'P': 3,
  'Q': 2,
  'R': 4,
  'S': 14,
  'V': 1},
 3: {'-': 169,
  'E': 2,
  'F': 61,
  'G': 7,
  'H': 8,
  'I': 6,
  'L': 4,
  'M': 10,
  'P': 12,
  'R': 3,
  'T': 1,
  'Y': 3},
 4: {'-': 160,
  'A': 6,
  'G': 78,
  'H': 3,
  'I': 1,
  'M': 18,
  'N': 3,
  'P': 1,
  'Q': 2,
  'R': 2,
  'S': 3,
  'T': 9},
 5: {'-': 152,
  'A': 15,
  'D': 6,
  'E': 7,
  'G': 19,
  'K': 6,
  'L': 6,
  'M': 13,
  'N': 1,
  'P': 29,
  'Q': 4,
  'R': 15,
  'S': 3,
  'T': 4,
  'V': 2,
  'Y': 4},
 6: {'-': 141,
  'A': 15,
  'K': 8,
  'M': 5,
  'N': 29,
  'P': 2,
  'Q': 6,
  'R': 26,
  'S': 28,
  'T': 26},
 7: {'-': 133,
  'A': 3,
  'F': 1,
  'G': 56,
  'I': 14,
  'K': 2,
  'L': 30,
  'M': 21,
  'P': 8,
  'Q': 3,
  'R': 2,
  'S': 1,
  'T': 9,
  'V': 3},
 8: {'-': 133,
  'A': 18,
  'G': 8,
  'H': 7,
  'I': 1,
  'K': 3,
  'N': 9,
  'P': 67,
  'Q': 3,
  'R': 15,
  'S': 5,
  'T': 14,
  'V': 3},
 9: {'-': 131,
  'A': 2,
  'G': 4,
  'I': 8,
  'K': 2,
  'L': 22,
  'M': 19,
  'N': 7,
  'P': 1,
  'Q': 28,
  'R': 4,
  'S': 41,
  'T': 16,
  'V': 1},
 10: {'-': 138,
  'A': 1,
  'G': 20,
  'H': 2,
  'I': 2,
  'K': 12,
  'N': 10,
  'P': 66,
  'Q': 8,
  'R': 5,
  'S': 1,
  'T': 20,
  'V': 1},
 11: {'-': 115,
  'A': 9,
  'G': 1,
  'K': 1,
  'L': 16,
  'M': 28,
  'N': 5,
  'Q': 2,
  'R': 1,
  'S': 60,
  'T': 45,
  'V': 3},
 12: {'-': 114,
  'A': 3,
  'D': 2,
  'E': 1,
  'G': 1,
  'H': 1,
  'I': 2,
  'K': 27,
  'L': 1,
  'M': 2,
  'N': 1,
  'P': 3,
  'Q': 1,
  'R': 4,
  'S': 14,
  'T': 88,
  'V': 20,
  'Y': 1},
 13: {'-': 109,
  'A': 2,
  'D': 6,
  'G': 1,
  'H': 2,
  'I': 9,
  'K': 6,
  'L': 40,
  'M': 38,
  'N': 14,
  'Q': 16,
  'S': 32,
  'T': 9,
  'V': 1,
  'Y': 1},
 14: {'-': 107,
  'A': 3,
  'D': 1,
  'E': 9,
  'G': 2,
  'H': 1,
  'I': 1,
  'K': 10,
  'M': 1,
  'N': 9,
  'Q': 20,
  'R': 1,
  'S': 67,
  'T': 45,
  'V': 8,
  'Y': 1},
 15: {'-': 98, 'G': 1, 'H': 121, 'K': 60, 'N': 2, 'Q': 1, 'S': 3},
 16: {'-': 90,
  'A': 3,
  'D': 96,
  'E': 14,
  'H': 3,
  'K': 9,
  'N': 21,
  'Q': 30,
  'R': 5,
  'S': 9,
  'T': 5,
  'V': 1},
 17: {'-': 53, 'F': 226, 'L': 6, 'V': 1},
 18: {'-': 53, 'A': 13, 'D': 1, 'G': 1, 'N': 5, 'S': 209, 'T': 4},
 19: {'-': 50,
  'A': 2,
  'D': 2,
  'E': 23,
  'H': 8,
  'K': 41,
  'M': 12,
  'N': 3,
  'Q': 39,
  'R': 101,
  'S': 1,
  'V': 4},
 20: {'-': 43,
  'A': 21,
  'G': 6,
  'I': 31,
  'L': 9,
  'N': 2,
  'S': 24,
  'T': 4,
  'V': 146},
 21: {'-': 48, 'A': 31, 'G': 1, 'K': 2, 'P': 192, 'S': 10, 'T': 2},
 22: {'-': 45,
  'A': 6,
  'G': 1,
  'H': 16,
  'I': 1,
  'K': 93,
  'L': 5,
  'M': 32,
  'N': 7,
  'Q': 24,
  'R': 29,
  'S': 10,
  'T': 9,
  'V': 8},
 23: {'-': 45,
  'A': 148,
  'G': 3,
  'I': 3,
  'K': 10,
  'P': 31,
  'R': 2,
  'S': 3,
  'T': 2,
  'V': 39},
 24: {'-': 45,
  'A': 4,
  'D': 78,
  'E': 73,
  'H': 1,
  'K': 8,
  'N': 45,
  'Q': 2,
  'R': 25,
  'S': 4,
  'V': 1},
 25: {'-': 43,
  'A': 1,
  'H': 1,
  'I': 178,
  'L': 1,
  'M': 4,
  'P': 37,
  'S': 1,
  'T': 9,
  'V': 5,
  'Y': 6},
 26: {'-': 43,
  'A': 11,
  'E': 12,
  'G': 1,
  'K': 3,
  'N': 2,
  'P': 54,
  'Q': 146,
  'R': 3,
  'S': 10,
  'T': 1},
 27: {'-': 41,
  'E': 3,
  'H': 15,
  'K': 1,
  'Q': 1,
  'R': 203,
  'S': 15,
  'T': 3,
  'Y': 4},
 28: {'-': 41, 'A': 1, 'D': 1, 'G': 3, 'N': 36, 'S': 203, 'Y': 1},
 29: {'-': 38,
  'A': 3,
  'H': 1,
  'I': 12,
  'K': 12,
  'M': 1,
  'Q': 6,
  'R': 3,
  'S': 58,
  'T': 84,
  'V': 68},
 30: {'-': 38, 'F': 238, 'H': 7, 'Y': 3},
 31: {'-': 38,
  'A': 1,
  'D': 117,
  'K': 12,
  'N': 108,
  'Q': 1,
  'R': 3,
  'S': 5,
  'V': 1},
 32: {'-': 38, 'A': 9, 'I': 2, 'L': 48, 'M': 2, 'R': 185, 'S': 1, 'T': 1},
 33: {'-': 38,
  'D': 68,
  'E': 1,
  'G': 2,
  'I': 1,
  'N': 3,
  'P': 1,
  'Q': 11,
  'S': 140,
  'T': 11,
  'V': 10},
 34: {'-': 38,
  'A': 1,
  'C': 1,
  'E': 1,
  'F': 10,
  'H': 206,
  'K': 6,
  'M': 1,
  'N': 3,
  'S': 4,
  'T': 5,
  'W': 1,
  'Y': 9},
 35: {'-': 31,
  'A': 6,
  'D': 31,
  'G': 181,
  'H': 1,
  'I': 3,
  'Q': 4,
  'S': 14,
  'T': 12,
  'V': 2,
  'Y': 1},
 36: {'-': 34,
  'A': 2,
  'C': 1,
  'F': 10,
  'H': 23,
  'I': 1,
  'K': 6,
  'L': 128,
  'M': 1,
  'N': 2,
  'R': 35,
  'V': 23,
  'W': 7,
  'Y': 13},
 37: {'-': 34, 'D': 1, 'G': 1, 'K': 236, 'L': 8, 'R': 6},
 38: {'-': 33,
  'A': 7,
  'F': 32,
  'G': 2,
  'L': 2,
  'M': 5,
  'S': 10,
  'T': 194,
  'Y': 1},
 39: {'-': 33, 'A': 20, 'D': 1, 'G': 6, 'S': 45, 'T': 179, 'V': 2},
 40: {'-': 33,
  'A': 1,
  'C': 1,
  'F': 136,
  'G': 16,
  'I': 39,
  'L': 12,
  'M': 43,
  'S': 4,
  'T': 1},
 41: {'-': 28,
  'A': 5,
  'D': 166,
  'H': 1,
  'K': 17,
  'N': 23,
  'Q': 8,
  'R': 8,
  'S': 23,
  'T': 6,
  'Y': 1},
 42: {'-': 27,
  'A': 156,
  'D': 1,
  'F': 1,
  'G': 4,
  'I': 39,
  'L': 5,
  'M': 12,
  'Q': 1,
  'S': 38,
  'T': 1,
  'V': 1},
 43: {'-': 27, 'D': 8, 'G': 240, 'N': 10, 'S': 1},
 44: {'-': 26,
  'A': 1,
  'D': 16,
  'E': 39,
  'F': 10,
  'H': 1,
  'K': 45,
  'L': 4,
  'N': 8,
  'Q': 10,
  'R': 7,
  'T': 7,
  'V': 2,
  'W': 5,
  'Y': 105},
 45: {'-': 26, 'I': 22, 'L': 236, 'M': 1, 'V': 1},
 46: {'-': 26, 'I': 68, 'M': 12, 'T': 28, 'V': 114, 'Y': 38},
 47: {'-': 26, 'I': 1, 'P': 253, 'T': 6},
 48: {'-': 26, 'C': 2, 'F': 17, 'I': 212, 'M': 1, 'T': 9, 'V': 19},
 49: {'-': 26,
  'C': 5,
  'F': 114,
  'G': 2,
  'I': 1,
  'L': 47,
  'M': 9,
  'N': 1,
  'Q': 1,
  'S': 23,
  'T': 6,
  'V': 1,
  'Y': 50},
 50: {'-': 24,
  'A': 8,
  'C': 12,
  'D': 1,
  'F': 16,
  'H': 1,
  'I': 12,
  'L': 12,
  'M': 6,
  'Q': 1,
  'S': 6,
  'T': 14,
  'V': 130,
  'W': 2,
  'Y': 41},
 51: {'-': 24,
  'D': 195,
  'E': 7,
  'G': 2,
  'I': 1,
  'L': 12,
  'M': 23,
  'N': 2,
  'Q': 7,
  'T': 12,
  'V': 1},
 52: {'-': 24,
  'D': 3,
  'E': 230,
  'F': 1,
  'L': 5,
  'M': 1,
  'N': 12,
  'P': 6,
  'Q': 3,
  'V': 1},
 53: {'-': 24,
  'A': 134,
  'C': 39,
  'G': 1,
  'I': 9,
  'M': 2,
  'T': 6,
  'V': 70,
  'Y': 1},
 54: {'-': 24, 'F': 1, 'I': 8, 'L': 187, 'M': 9, 'Q': 2, 'V': 50, 'Y': 5},
 55: {'-': 22, 'A': 6, 'E': 2, 'P': 256},
 56: {'-': 22, 'A': 11, 'G': 248, 'S': 3, 'T': 1, 'Y': 1},
 57: {'-': 24, 'D': 259, 'E': 1, 'G': 1, 'Q': 1},
 58: {'-': 23,
  'A': 1,
  'D': 1,
  'E': 1,
  'K': 23,
  'L': 1,
  'N': 1,
  'R': 3,
  'S': 46,
  'T': 186},
 59: {'-': 23,
  'A': 1,
  'C': 1,
  'F': 234,
  'H': 2,
  'I': 4,
  'K': 1,
  'L': 3,
  'M': 8,
  'S': 1,
  'V': 4,
  'Y': 4},
 60: {'-': 22,
  'D': 15,
  'E': 7,
  'H': 1,
  'K': 18,
  'L': 1,
  'N': 89,
  'Q': 67,
  'R': 1,
  'S': 32,
  'T': 32,
  'V': 1},
 61: {'-': 22,
  'A': 1,
  'C': 28,
  'F': 1,
  'G': 1,
  'H': 1,
  'I': 52,
  'L': 104,
  'M': 39,
  'Q': 1,
  'S': 8,
  'T': 3,
  'V': 25},
 62: {'-': 22,
  'A': 2,
  'D': 47,
  'E': 10,
  'H': 1,
  'K': 60,
  'N': 74,
  'Q': 3,
  'R': 22,
  'S': 22,
  'T': 23},
 63: {'-': 22,
  'A': 105,
  'C': 2,
  'G': 1,
  'L': 16,
  'M': 74,
  'P': 5,
  'Q': 1,
  'S': 25,
  'T': 35},
 64: {'-': 21,
  'A': 2,
  'D': 2,
  'E': 3,
  'F': 2,
  'H': 31,
  'I': 1,
  'M': 1,
  'N': 39,
  'Q': 1,
  'R': 3,
  'S': 30,
  'T': 144,
  'V': 6},
 65: {'-': 21,
  'A': 63,
  'C': 6,
  'F': 9,
  'G': 115,
  'H': 1,
  'I': 7,
  'L': 8,
  'M': 2,
  'N': 27,
  'Q': 16,
  'S': 7,
  'T': 2,
  'V': 2},
 66: {'-': 21, 'A': 6, 'D': 6, 'F': 196, 'I': 3, 'L': 38, 'M': 12, 'V': 4},
 67: {'-': 21,
  'A': 67,
  'C': 4,
  'F': 1,
  'G': 114,
  'I': 2,
  'L': 24,
  'M': 1,
  'S': 5,
  'T': 27,
  'V': 20},
 68: {'-': 19, 'E': 1, 'K': 7, 'N': 1, 'R': 258},
 69: {'-': 18, 'F': 50, 'I': 4, 'L': 191, 'M': 13, 'T': 6, 'V': 3, 'Y': 1},
 70: {'-': 18, 'A': 220, 'D': 1, 'L': 6, 'M': 1, 'N': 10, 'S': 30},
 71: {'-': 18, 'N': 2, 'P': 64, 'T': 201, 'V': 1},
 72: {'-': 18, 'A': 2, 'D': 1, 'L': 45, 'M': 15, 'P': 198, 'S': 1, 'T': 6},
 73: {'-': 18,
  'A': 2,
  'E': 1,
  'I': 174,
  'L': 66,
  'M': 1,
  'N': 1,
  'R': 8,
  'V': 15},
 74: {'-': 18,
  'A': 37,
  'E': 1,
  'F': 29,
  'G': 6,
  'H': 50,
  'K': 5,
  'N': 83,
  'R': 6,
  'S': 3,
  'T': 16,
  'V': 13,
  'Y': 19},
 75: {'-': 18, 'G': 6, 'P': 262},
 76: {'-': 18,
  'C': 2,
  'F': 70,
  'I': 115,
  'L': 23,
  'N': 1,
  'T': 10,
  'V': 34,
  'Y': 13},
 77: {'-': 15, 'A': 6, 'F': 7, 'I': 11, 'L': 8, 'M': 237, 'V': 2},
 78: {'-': 15, 'D': 202, 'E': 3, 'G': 7, 'H': 53, 'I': 6},
 79: {'-': 11,
  'D': 6,
  'E': 15,
  'K': 18,
  'N': 204,
  'P': 2,
  'Q': 14,
  'R': 4,
  'S': 11,
  'T': 1},
 80: {'-': 11,
  'A': 33,
  'C': 2,
  'F': 1,
  'I': 17,
  'L': 106,
  'M': 75,
  'S': 27,
  'T': 2,
  'V': 6,
  'Y': 6},
 81: {'-': 11,
  'A': 7,
  'D': 1,
  'E': 1,
  'F': 32,
  'H': 22,
  'K': 20,
  'M': 2,
  'N': 2,
  'Q': 2,
  'R': 1,
  'S': 42,
  'T': 9,
  'Y': 134},
 82: {'-': 11, 'A': 7, 'F': 3, 'I': 79, 'L': 41, 'M': 58, 'Q': 2, 'V': 85},
 83: {'-': 14,
  'D': 89,
  'E': 81,
  'F': 1,
  'N': 4,
  'Q': 37,
  'R': 3,
  'S': 4,
  'T': 5,
  'Y': 48},
 84: {'-': 15,
  'C': 29,
  'F': 1,
  'I': 19,
  'L': 6,
  'M': 1,
  'Q': 1,
  'S': 22,
  'T': 182,
  'V': 10},
 85: {'-': 15, 'A': 1, 'D': 7, 'F': 148, 'H': 99, 'Q': 6, 'Y': 10},
 86: {'-': 15,
  'A': 1,
  'F': 215,
  'G': 1,
  'H': 5,
  'T': 6,
  'V': 6,
  'W': 6,
  'Y': 31},
 87: {'-': 15, 'F': 266, 'I': 2, 'T': 1, 'W': 2},
 88: {'-': 15, 'A': 101, 'E': 7, 'F': 109, 'G': 1, 'S': 33, 'T': 1, 'Y': 19},
 89: {'-': 15, 'A': 1, 'C': 11, 'I': 11, 'T': 1, 'V': 247},
 90: {'-': 14, 'A': 2, 'L': 1, 'P': 268, 'Q': 1},
 91: {'-': 14,
  'F': 25,
  'G': 1,
  'H': 11,
  'I': 12,
  'K': 2,
  'L': 4,
  'M': 17,
  'N': 109,
  'S': 3,
  'T': 7,
  'V': 17,
  'Y': 64},
 92: {'-': 14, 'E': 1, 'R': 270, 'V': 1},
 93: {'-': 14, 'A': 1, 'H': 6, 'I': 89, 'L': 173, 'Q': 2, 'T': 1},
 94: {'-': 14, 'D': 1, 'F': 1, 'I': 82, 'L': 97, 'V': 85, 'Y': 6},
 95: {'-': 13, 'F': 2, 'N': 3, 'Q': 3, 'W': 258, 'Y': 7},
 96: {'-': 13,
  'A': 1,
  'D': 159,
  'E': 14,
  'G': 6,
  'L': 1,
  'N': 31,
  'P': 17,
  'S': 22,
  'T': 20,
  'V': 2},
 97: {'-': 20, 'D': 15, 'E': 7, 'H': 1, 'K': 12, 'N': 218, 'Q': 11, 'S': 2},
 98: {'-': 20, 'F': 31, 'G': 3, 'H': 2, 'S': 1, 'W': 228, 'Y': 1},
 99: {'-': 17,
  'A': 3,
  'E': 152,
  'F': 3,
  'I': 6,
  'K': 10,
  'Q': 86,
  'R': 5,
  'S': 1,
  'V': 3},
 100: {'-': 11,
  'A': 1,
  'D': 26,
  'E': 26,
  'G': 1,
  'K': 179,
  'L': 1,
  'N': 5,
  'P': 1,
  'R': 25,
  'S': 3,
  'T': 5,
  'Y': 2},
 101: {'-': 9,
  'F': 234,
  'G': 1,
  'I': 1,
  'L': 10,
  'M': 10,
  'S': 3,
  'T': 2,
  'Y': 16},
 102: {'-': 9,
  'C': 77,
  'F': 1,
  'G': 13,
  'H': 10,
  'I': 31,
  'L': 2,
  'M': 63,
  'N': 67,
  'Q': 2,
  'S': 7,
  'T': 4},
 103: {'-': 11, 'G': 228, 'K': 6, 'M': 6, 'S': 10, 'T': 25},
 104: {'-': 11,
  'A': 32,
  'D': 9,
  'E': 177,
  'G': 36,
  'N': 8,
  'P': 2,
  'Q': 7,
  'S': 2,
  'T': 1,
  'V': 1},
 105: {'-': 12,
  'A': 1,
  'D': 12,
  'E': 5,
  'G': 36,
  'K': 4,
  'L': 1,
  'M': 6,
  'N': 2,
  'P': 1,
  'Q': 173,
  'R': 21,
  'T': 10,
  'V': 2},
 106: {'-': 12,
  'A': 7,
  'D': 88,
  'E': 34,
  'G': 8,
  'H': 1,
  'I': 28,
  'K': 3,
  'L': 11,
  'N': 5,
  'P': 2,
  'Q': 8,
  'R': 4,
  'S': 2,
  'T': 42,
  'V': 31},
 107: {'-': 12,
  'A': 8,
  'D': 92,
  'E': 2,
  'G': 7,
  'K': 3,
  'M': 1,
  'N': 151,
  'P': 1,
  'T': 2,
  'Y': 7},
 108: {'-': 19,
  'A': 16,
  'D': 5,
  'G': 23,
  'I': 5,
  'L': 7,
  'N': 1,
  'P': 196,
  'Q': 1,
  'S': 4,
  'T': 7,
  'V': 1,
  'Y': 1},
 109: {'-': 18,
  'A': 33,
  'D': 27,
  'E': 1,
  'F': 2,
  'G': 145,
  'L': 14,
  'N': 20,
  'P': 4,
  'Q': 2,
  'S': 4,
  'T': 10,
  'V': 2,
  'W': 3,
  'Y': 1},
 110: {'-': 12,
  'A': 1,
  'D': 214,
  'E': 4,
  'G': 5,
  'N': 1,
  'P': 7,
  'Q': 5,
  'S': 33,
  'T': 3,
  'Y': 1},
 111: {'-': 13,
  'A': 13,
  'D': 5,
  'E': 5,
  'G': 3,
  'L': 5,
  'M': 6,
  'N': 3,
  'P': 16,
  'S': 196,
  'T': 11,
  'V': 6,
  'Y': 4},
 112: {'-': 13,
  'A': 3,
  'F': 6,
  'G': 11,
  'I': 71,
  'P': 14,
  'S': 16,
  'T': 148,
  'V': 4},
 113: {'-': 29,
  'A': 11,
  'D': 184,
  'E': 13,
  'G': 1,
  'H': 1,
  'K': 2,
  'N': 5,
  'P': 18,
  'S': 17,
  'T': 4,
  'V': 1},
 114: {'-': 30,
  'A': 1,
  'F': 56,
  'H': 1,
  'I': 3,
  'L': 3,
  'N': 1,
  'P': 10,
  'Q': 3,
  'T': 7,
  'V': 12,
  'W': 1,
  'Y': 158},
 115: {'-': 26,
  'A': 5,
  'F': 1,
  'G': 1,
  'I': 16,
  'K': 2,
  'L': 129,
  'M': 7,
  'P': 6,
  'Q': 16,
  'R': 1,
  'S': 3,
  'T': 49,
  'V': 14,
  'Y': 10},
 116: {'-': 22,
  'A': 1,
  'C': 2,
  'F': 13,
  'I': 76,
  'L': 13,
  'M': 3,
  'N': 1,
  'P': 13,
  'S': 2,
  'T': 26,
  'V': 114},
 117: {'-': 10, 'F': 1, 'G': 1, 'K': 1, 'L': 5, 'P': 264, 'S': 4},
 118: {'-': 15,
  'A': 1,
  'D': 1,
  'E': 7,
  'F': 1,
  'G': 1,
  'I': 8,
  'K': 1,
  'L': 5,
  'N': 1,
  'P': 12,
  'Q': 116,
  'R': 4,
  'S': 1,
  'T': 96,
  'V': 11,
  'Y': 5},
 119: {'-': 20,
  'A': 2,
  'C': 2,
  'F': 4,
  'G': 1,
  'I': 105,
  'L': 20,
  'M': 32,
  'N': 1,
  'Q': 1,
  'S': 2,
  'T': 38,
  'V': 55,
  'Y': 3},
 120: {'-': 38,
  'A': 14,
  'C': 1,
  'D': 11,
  'E': 17,
  'F': 1,
  'G': 3,
  'I': 2,
  'K': 13,
  'L': 1,
  'N': 4,
  'Q': 47,
  'R': 2,
  'S': 27,
  'T': 93,
  'V': 12},
 121: {'-': 49,
  'A': 40,
  'D': 2,
  'E': 4,
  'F': 4,
  'G': 17,
  'I': 3,
  'L': 6,
  'M': 3,
  'N': 27,
  'P': 18,
  'Q': 2,
  'S': 63,
  'T': 43,
  'V': 5},
 122: {'-': 56,
  'A': 32,
  'D': 10,
  'G': 9,
  'H': 10,
  'I': 4,
  'K': 2,
  'L': 2,
  'N': 7,
  'P': 82,
  'Q': 3,
  'S': 10,
  'T': 31,
  'V': 12,
  'Y': 16},
 123: {'-': 22,
  'A': 67,
  'D': 3,
  'F': 10,
  'G': 15,
  'I': 1,
  'L': 7,
  'N': 7,
  'P': 6,
  'Q': 4,
  'S': 47,
  'T': 69,
  'V': 27,
  'Y': 1},
 124: {'-': 80,
  'A': 18,
  'D': 3,
  'E': 1,
  'G': 72,
  'I': 5,
  'K': 1,
  'L': 9,
  'N': 12,
  'P': 5,
  'S': 27,
  'T': 44,
  'V': 6,
  'W': 1,
  'Y': 2},
 125: {'-': 69,
  'A': 3,
  'D': 3,
  'E': 4,
  'F': 1,
  'G': 98,
  'N': 25,
  'P': 9,
  'Q': 11,
  'S': 18,
  'T': 39,
  'V': 1,
  'Y': 5},
 126: {'-': 37,
  'A': 15,
  'D': 7,
  'E': 2,
  'F': 13,
  'H': 7,
  'I': 28,
  'L': 16,
  'M': 10,
  'N': 2,
  'S': 3,
  'T': 4,
  'V': 82,
  'W': 2,
  'Y': 58},
 127: {'-': 31,
  'A': 88,
  'D': 8,
  'E': 7,
  'G': 5,
  'I': 3,
  'K': 3,
  'L': 21,
  'N': 6,
  'P': 31,
  'Q': 4,
  'S': 11,
  'T': 62,
  'V': 6},
 128: {'-': 28,
  'A': 7,
  'D': 3,
  'E': 84,
  'F': 1,
  'I': 11,
  'L': 7,
  'M': 1,
  'N': 31,
  'P': 15,
  'Q': 6,
  'S': 21,
  'T': 30,
  'V': 39,
  'Y': 2},
 129: {'-': 3,
  'A': 9,
  'D': 7,
  'E': 15,
  'G': 132,
  'K': 1,
  'L': 2,
  'N': 19,
  'Q': 30,
  'S': 62,
  'V': 6},
 130: {'-': 3,
  'A': 3,
  'D': 14,
  'E': 3,
  'G': 3,
  'M': 5,
  'N': 9,
  'Q': 3,
  'R': 1,
  'S': 132,
  'T': 109,
  'Y': 1},
 131: {'-': 2, 'F': 1, 'I': 32, 'L': 230, 'M': 10, 'N': 1, 'T': 6, 'V': 4},
 132: {'-': 2,
  'A': 28,
  'D': 2,
  'E': 5,
  'F': 64,
  'G': 14,
  'H': 7,
  'L': 8,
  'N': 1,
  'P': 14,
  'Q': 22,
  'R': 1,
  'S': 51,
  'T': 7,
  'W': 6,
  'Y': 54},
 133: {'-': 1, 'D': 270, 'E': 1, 'G': 6, 'N': 3, 'S': 5},
 134: {'-': 2, 'F': 4, 'H': 4, 'I': 1, 'K': 1, 'L': 1, 'N': 1, 'Y': 272},
 135: {'-': 2, 'F': 101, 'I': 20, 'L': 71, 'M': 90, 'V': 2},
 136: {'-': 3, 'A': 7, 'D': 1, 'G': 262, 'N': 11, 'Q': 2},
 137: {'-': 3, 'A': 7, 'F': 3, 'I': 83, 'L': 141, 'M': 2, 'P': 1, 'V': 46},
 138: {'-': 3,
  'A': 1,
  'F': 6,
  'G': 2,
  'P': 265,
  'Q': 2,
  'S': 1,
  'T': 4,
  'V': 2},
 139: {'-': 2,
  'A': 2,
  'D': 7,
  'E': 1,
  'I': 27,
  'L': 24,
  'N': 7,
  'P': 12,
  'R': 1,
  'S': 7,
  'T': 184,
  'V': 12},
 140: {'-': 2,
  'A': 15,
  'D': 29,
  'E': 7,
  'G': 129,
  'H': 1,
  'K': 46,
  'L': 7,
  'N': 13,
  'Q': 20,
  'R': 1,
  'S': 12,
  'T': 4},
 141: {'-': 25,
  'A': 12,
  'C': 1,
  'D': 3,
  'E': 1,
  'F': 5,
  'G': 3,
  'H': 1,
  'I': 43,
  'K': 2,
  'L': 3,
  'M': 1,
  'N': 13,
  'Q': 4,
  'S': 15,
  'T': 27,
  'V': 120,
  'Y': 7},
 142: {'-': 46,
  'A': 82,
  'D': 16,
  'E': 9,
  'G': 11,
  'H': 3,
  'I': 6,
  'K': 12,
  'L': 10,
  'N': 21,
  'P': 19,
  'Q': 12,
  'R': 1,
  'S': 21,
  'T': 11,
  'V': 3,
  'W': 1,
  'Y': 2},
 143: {'-': 7,
  'A': 25,
  'D': 20,
  'E': 2,
  'G': 84,
  'I': 5,
  'K': 3,
  'L': 6,
  'M': 1,
  'N': 51,
  'P': 3,
  'Q': 2,
  'R': 1,
  'S': 50,
  'T': 25,
  'Y': 1},
 144: {'-': 3,
  'A': 14,
  'D': 6,
  'E': 3,
  'F': 3,
  'G': 2,
  'I': 55,
  'L': 118,
  'M': 2,
  'N': 1,
  'P': 10,
  'Q': 4,
  'R': 3,
  'S': 1,
  'T': 25,
  'V': 30,
  'W': 3,
  'Y': 3},
 145: {'-': 2,
  'A': 6,
  'D': 30,
  'E': 39,
  'G': 2,
  'K': 8,
  'L': 2,
  'N': 22,
  'P': 7,
  'Q': 14,
  'R': 3,
  'S': 73,
  'T': 74,
  'V': 3,
  'Y': 1},
 146: {'-': 1,
  'A': 8,
  'F': 95,
  'G': 1,
  'H': 72,
  'I': 39,
  'L': 1,
  'M': 1,
  'N': 1,
  'P': 2,
  'S': 1,
  'T': 9,
  'V': 27,
  'W': 19,
  'Y': 9},
 147: {'A': 2,
  'C': 4,
  'D': 2,
  'I': 1,
  'M': 1,
  'N': 145,
  'S': 127,
  'T': 3,
  'V': 1},
 148: {'-': 1,
  'A': 110,
  'C': 13,
  'D': 2,
  'G': 5,
  'I': 1,
  'K': 6,
  'M': 1,
  'N': 108,
  'P': 1,
  'S': 23,
  'T': 10,
  'V': 5},
 149: {'-': 1,
  'E': 1,
  'F': 29,
  'I': 14,
  'L': 197,
  'M': 19,
  'S': 1,
  'V': 11,
  'W': 12,
  'Y': 1},
 150: {'-': 2,
  'A': 45,
  'C': 12,
  'F': 29,
  'H': 28,
  'I': 1,
  'L': 2,
  'M': 2,
  'N': 1,
  'P': 85,
  'S': 3,
  'V': 7,
  'W': 55,
  'Y': 14},
 151: {'-': 2,
  'A': 3,
  'F': 72,
  'G': 105,
  'H': 57,
  'I': 5,
  'L': 8,
  'M': 2,
  'N': 4,
  'Q': 1,
  'R': 1,
  'S': 3,
  'T': 14,
  'V': 3,
  'Y': 6},
 152: {'-': 2,
  'A': 30,
  'C': 1,
  'G': 1,
  'I': 1,
  'L': 8,
  'M': 17,
  'N': 1,
  'Q': 6,
  'R': 218,
  'S': 1},
 153: {'-': 2, 'A': 229, 'C': 6, 'G': 23, 'M': 7, 'S': 19},
 154: {'-': 2,
  'F': 3,
  'H': 3,
  'I': 1,
  'L': 1,
  'M': 1,
  'V': 1,
  'W': 1,
  'Y': 273},
 155: {'-': 2,
  'A': 5,
  'D': 1,
  'G': 2,
  'H': 2,
  'K': 1,
  'L': 8,
  'N': 213,
  'Q': 15,
  'R': 2,
  'S': 4,
  'T': 14,
  'W': 16,
  'Y': 1},
 156: {'-': 2,
  'D': 6,
  'F': 2,
  'H': 2,
  'I': 6,
  'K': 55,
  'L': 193,
  'M': 3,
  'N': 6,
  'Q': 2,
  'R': 4,
  'S': 2,
  'T': 3},
 157: {'-': 2, 'C': 20, 'I': 231, 'S': 1, 'V': 32},
 158: {'-': 2, 'A': 1, 'F': 25, 'H': 1, 'W': 121, 'Y': 136},
 159: {'-': 2,
  'D': 1,
  'K': 6,
  'N': 266,
  'Q': 5,
  'R': 1,
  'S': 1,
  'T': 3,
  'Y': 1},
 160: {'-': 1,
  'C': 2,
  'D': 80,
  'E': 174,
  'G': 1,
  'H': 2,
  'L': 1,
  'N': 11,
  'Q': 6,
  'T': 8},
 161: {'-': 1, 'A': 1, 'F': 2, 'H': 1, 'T': 2, 'W': 214, 'Y': 65},
 162: {'-': 1, 'F': 205, 'V': 1, 'Y': 79},
 163: {'-': 2, 'A': 6, 'K': 11, 'M': 6, 'R': 261},
 164: {'-': 8, 'A': 2, 'D': 265, 'N': 7, 'S': 4},
 165: {'-': 8,
  'D': 1,
  'E': 176,
  'G': 1,
  'K': 3,
  'Q': 94,
  'S': 1,
  'T': 1,
  'Y': 1},
 166: {'-': 8, 'D': 7, 'E': 1, 'N': 260, 'Q': 3, 'S': 2, 'T': 3, 'W': 2},
 167: {'-': 9, 'E': 2, 'I': 5, 'L': 260, 'M': 4, 'S': 1, 'T': 3, 'V': 2},
 168: {'-': 15,
  'A': 1,
  'C': 8,
  'D': 1,
  'F': 1,
  'I': 30,
  'Q': 201,
  'S': 4,
  'T': 1,
  'V': 23,
  'Y': 1},
 169: {'-': 19,
  'A': 1,
  'D': 159,
  'G': 1,
  'H': 2,
  'K': 1,
  'L': 1,
  'N': 63,
  'P': 9,
  'Q': 6,
  'S': 5,
  'T': 18,
  'V': 1},
 170: {'-': 15,
  'A': 4,
  'D': 2,
  'E': 10,
  'F': 14,
  'K': 23,
  'N': 4,
  'P': 9,
  'Q': 1,
  'S': 189,
  'T': 14,
  'V': 1},
 171: {'-': 30,
  'A': 9,
  'D': 3,
  'E': 1,
  'F': 2,
  'G': 2,
  'I': 15,
  'K': 16,
  'L': 76,
  'P': 1,
  'Q': 8,
  'R': 1,
  'S': 3,
  'T': 10,
  'V': 109},
 172: {'-': 26,
  'A': 3,
  'D': 11,
  'E': 3,
  'F': 2,
  'G': 5,
  'I': 2,
  'K': 1,
  'N': 6,
  'P': 30,
  'Q': 4,
  'R': 1,
  'S': 7,
  'T': 129,
  'V': 54,
  'Y': 2},
 173: {'-': 24,
  'A': 5,
  'D': 8,
  'E': 2,
  'F': 5,
  'I': 6,
  'K': 1,
  'L': 15,
  'M': 14,
  'P': 1,
  'S': 1,
  'T': 10,
  'V': 192,
  'Y': 2},
 174: {'-': 23,
  'A': 1,
  'D': 139,
  'E': 5,
  'G': 2,
  'H': 2,
  'I': 3,
  'K': 8,
  'L': 13,
  'N': 17,
  'P': 23,
  'Q': 1,
  'R': 1,
  'S': 28,
  'T': 12,
  'V': 8},
 175: {'-': 25,
  'A': 7,
  'C': 1,
  'D': 9,
  'E': 1,
  'H': 1,
  'I': 8,
  'K': 108,
  'L': 34,
  'M': 2,
  'P': 1,
  'R': 25,
  'T': 43,
  'V': 20,
  'W': 1},
 176: {'-': 17,
  'A': 10,
  'D': 69,
  'E': 1,
  'G': 118,
  'I': 4,
  'K': 17,
  'L': 1,
  'N': 2,
  'S': 9,
  'T': 31,
  'V': 6,
  'Y': 1},

In [23]:
# get lake and ocean specific top features

lake_top_feats = important.loc[important['biome_predictor'] == "lake"].sort_values('feature_importance_vals', ascending=False).head(n=TOP)
ocean_top_feats = important.loc[important['biome_predictor'] == "ocean"].sort_values('feature_importance_vals', ascending=False).head(n=TOP)
ocean_top_feats.head(n=5)

# write out amino acid counts in the top X features
ocean_top_feats[['position','aa']]=ocean_top_feats['feature'].str.split("_", expand=True)
lake_top_feats[['position','aa']]=lake_top_feats['feature'].str.split("_", expand=True)
amino_acid_counts_in_feats = ocean_top_feats.groupby(['aa'])['position'].count()
amino_acid_counts_in_feats.to_csv(f"ocean_aa_counts_in{TOP}_features_NEW.csv")
amino_acid_counts_in_feats = lake_top_feats.groupby(['aa'])['position'].count()
amino_acid_counts_in_feats.to_csv(f"lake_aa_counts_in{TOP}_features_NEW.csv")

In [24]:
# get amino acids by position mapping between top_feats dataframe and the OTHER biome msa
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ocean-important features
ocean_store_seqs = defaultdict(lambda: defaultdict(list))
ocean_store_proportions = defaultdict(lambda: defaultdict(list))
ocean_store_featcounts = defaultdict(lambda: defaultdict(list))

for index, row in ocean_top_feats.iterrows():
    feat_pos = int(row[1].split("_")[0])
    feat_AA = row[1].split("_")[1]

    total = sum(v for k, v in lake_msa_map_dict[feat_pos].items() if k not in ["X", "-"])

    for other_aa in lake_msa_map_dict[feat_pos]:
        if other_aa in ["X", "-"]:
            continue

        seqs = lake_msa_map_dict[feat_pos][other_aa]
        proportion = seqs / total

        ocean_store_seqs[feat_AA][other_aa].append(seqs)
        ocean_store_proportions[feat_AA][other_aa].append(proportion)  # was appending seqs here
        ocean_store_featcounts[feat_AA][other_aa].append(1)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# lake-important features
lake_store_seqs = defaultdict(lambda: defaultdict(list))
lake_store_proportions = defaultdict(lambda: defaultdict(list))
lake_store_featcounts = defaultdict(lambda: defaultdict(list))

for index, row in lake_top_feats.iterrows():
    feat_pos = int(row[1].split("_")[0])
    feat_AA = row[1].split("_")[1]

    total = sum(v for k, v in ocean_msa_map_dict[feat_pos].items() if k not in ["X", "-"])

    for other_aa in ocean_msa_map_dict[feat_pos]:
        if other_aa in ["X", "-"]:
            continue

        seqs = ocean_msa_map_dict[feat_pos][other_aa]
        proportion = seqs / total

        lake_store_seqs[feat_AA][other_aa].append(seqs)
        lake_store_proportions[feat_AA][other_aa].append(proportion)  # was appending seqs here
        lake_store_featcounts[feat_AA][other_aa].append(1)

/var/folders/6c/dkl_rmf913l9h4s3pys_spm80000gn/T/ipykernel_77543/1974608872.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  feat_pos = int(row[1].split("_")[0])
/var/folders/6c/dkl_rmf913l9h4s3pys_spm80000gn/T/ipykernel_77543/1974608872.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  feat_AA = row[1].split("_")[1]
/var/folders/6c/dkl_rmf913l9h4s3pys_spm80000gn/T/ipykernel_77543/1974608872.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  feat_pos = int(row[1].split("_")[0])
/var/folders/6c/dkl_rmf913l9h4s3pys_spm80000gn/T/ipykernel_77543/1974608872.py:33: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  feat_AA = row[1].split("_")[1]

In [25]:
# either sum (for number of seqs or feat counts) or average (proportions) the lists in storage dictionaries
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ocean-important features
ocean_store_seqs_sum = defaultdict(dict)
ocean_store_proportions_avg = defaultdict(dict)
ocean_store_featcounts_sum = defaultdict(dict)

for feat_AA,v in ocean_store_seqs.items():
    for other_AA,seqs in v.items():
        # print(seqs)
        ocean_store_seqs_sum[feat_AA][other_AA] = sum(seqs)

ocean_seqs_mat = pd.DataFrame.from_dict(ocean_store_seqs_sum)

for feat_AA,v in ocean_store_proportions.items():
    for other_AA,proportions in v.items():
        # print(seqs)
        ocean_store_proportions_avg[feat_AA][other_AA] = st.fmean(proportions)

ocean_proportions_mat = pd.DataFrame.from_dict(ocean_store_proportions_avg)

for feat_AA,v in ocean_store_featcounts.items():
    for other_AA,counts in v.items():
        # print(seqs)
        ocean_store_featcounts_sum[feat_AA][other_AA] = sum(counts)

ocean_featcounts_mat = pd.DataFrame.from_dict(ocean_store_featcounts_sum)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# lake-important features
lake_store_seqs_sum = defaultdict(dict)
lake_store_proportions_avg = defaultdict(dict)
lake_store_featcounts_sum = defaultdict(dict)

for feat_AA,v in lake_store_seqs.items():
    for other_AA,seqs in v.items():
        # print(seqs)
        lake_store_seqs_sum[feat_AA][other_AA] = sum(seqs)

lake_seqs_mat = pd.DataFrame.from_dict(lake_store_seqs_sum)

for feat_AA,v in lake_store_proportions.items():
    for other_AA,proportions in v.items():
        # print(seqs)
        lake_store_proportions_avg[feat_AA][other_AA] = st.fmean(proportions)

lake_proportions_mat = pd.DataFrame.from_dict(lake_store_proportions_avg)

for feat_AA,v in lake_store_featcounts.items():
    for other_AA,counts in v.items():
        # print(seqs)
        lake_store_featcounts_sum[feat_AA][other_AA] = sum(counts)

lake_featcounts_mat = pd.DataFrame.from_dict(lake_store_featcounts_sum)

In [26]:
#Convert matrices to long-format dataframe
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ocean-important features
ocean_seqs_df = ocean_seqs_mat.reset_index(names="other_AA").melt(
    value_vars=["S",	"Q",	"D"	,"K",	"N",	"M",	"W",	"L"	,"F"	,"G"	,"Y"	,"H"	,"R",	"V"	,"E",	"P"	,"T",	"I"	,"C"	,"A"],
    var_name="feat_AA",
    value_name="seqs",
    id_vars=["other_AA"])

ocean_proportions_df = ocean_proportions_mat.reset_index(names="other_AA").melt(
    value_vars=["S",	"Q",	"D"	,"K",	"N",	"M",	"W",	"L"	,"F"	,"G"	,"Y"	,"H"	,"R",	"V"	,"E",	"P"	,"T",	"I"	,"C"	,"A"],
    var_name="feat_AA",
    value_name="proportion",
    id_vars=["other_AA"])

ocean_featcounts_df = ocean_featcounts_mat.reset_index(names="other_AA").melt(
    value_vars=["S",	"Q",	"D"	,"K",	"N",	"M",	"W",	"L"	,"F"	,"G"	,"Y"	,"H"	,"R",	"V"	,"E",	"P"	,"T",	"I"	,"C"	,"A"],
    var_name="feat_AA",
    value_name="feat_counts",
    id_vars=["other_AA"])

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# lake-important features
lake_seqs_df = lake_seqs_mat.reset_index(names="other_AA").melt(
    value_vars=["S",	"Q",	"D"	,"K",	"N",	"M",	"W",	"L"	,"F"	,"G"	,"Y"	,"H"	,"R",	"V"	,	"P"	,"T",	"I"	,"C"	,"A"],
    var_name="feat_AA",
    value_name="seqs",
    id_vars=["other_AA"])

lake_proportions_df = lake_proportions_mat.reset_index(names="other_AA").melt(
    value_vars=["S",	"Q",	"D"	,"K",	"N",	"M",	"W",	"L"	,"F"	,"G"	,"Y"	,"H"	,"R",	"V"	,	"P"	,"T",	"I"	,"C"	,"A"],
    var_name="feat_AA",
    value_name="proportion",
    id_vars=["other_AA"])

lake_featcounts_df = lake_featcounts_mat.reset_index(names="other_AA").melt(
    value_vars=["S",	"Q",	"D"	,"K",	"N",	"M",	"W",	"L"	,"F"	,"G"	,"Y"	,"H"	,"R",	"V"	,	"P"	,"T",	"I"	,"C"	,"A"],
    var_name="feat_AA",
    value_name="feat_counts",
    id_vars=["other_AA"])

In [27]:
print(ocean_seqs_df.shape)
print(ocean_proportions_df.shape)
print(ocean_featcounts_df.shape)

print(lake_seqs_df.shape)
print(lake_proportions_df.shape)
print(lake_featcounts_df.shape)

(400, 3)
(400, 3)
(400, 3)
(380, 3)
(380, 3)
(380, 3)

In [28]:
# merge all the dataframes to make one dataframe for heatmap
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ocean-important features
merged_df_1 = ocean_seqs_df.merge(ocean_proportions_df,
    how="left",
    left_on=["other_AA","feat_AA"],
    right_on=["other_AA","feat_AA"]
)

ocean_merged_df_2 = merged_df_1.merge(ocean_featcounts_df,
                                how="left",
                                left_on=["other_AA","feat_AA"],
                                right_on=["other_AA","feat_AA"])
print(ocean_merged_df_2)
ocean_merged_df_2.to_csv(f"ocean_switch_df_for_heatmap_{TOP}_NEW.tsv",index=False, sep='\t')

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# lake-important features
merged_df_1 = lake_seqs_df.merge(lake_proportions_df,
    how="left",
    left_on=["other_AA","feat_AA"],
    right_on=["other_AA","feat_AA"]
)

lake_merged_df_2 = merged_df_1.merge(lake_featcounts_df,
                                how="left",
                                left_on=["other_AA","feat_AA"],
                                right_on=["other_AA","feat_AA"])
print(lake_merged_df_2)
lake_merged_df_2.to_csv(f"lake_switch_df_for_heatmap_{TOP}_NEW.tsv",index=False, sep='\t')

    other_AA feat_AA    seqs  proportion  feat_counts
0          A       S  2106.0    0.180745         15.0
1          F       S    54.0    0.021674          6.0
2          G       S  3794.0    0.330579         14.0
3          H       S   260.0    0.080753          8.0
4          I       S    35.0    0.006299          7.0
..       ...     ...     ...         ...          ...
395        E       A    32.0    0.010683          4.0
396        L       A    56.0    0.010270          7.0
397        D       A    97.0    0.032464          4.0
398        C       A   202.0    0.062520          4.0
399        W       A     3.0    0.003717          1.0

[400 rows x 5 columns]
    other_AA feat_AA   seqs  proportion  feat_counts
0          D       S  345.0    0.179665          8.0
1          F       S   57.0    0.034793          6.0
2          G       S  156.0    0.061135         10.0
3          H       S  258.0    0.256661          4.0
4          I       S   32.0    0.023784          5.0
..       ...     ...    ...         ...          ...
375        E       A  102.0    0.047328          8.0
376        T       A  509.0    0.116885         17.0
377        V       A  169.0    0.048578         13.0
378        C       A   67.0    0.059299          4.0
379        P       A  219.0    0.104658          8.0

[380 rows x 5 columns]