In [2]:
import pandas as pd

## workflow

1. read in feature importances
2. read in surface areas
3. read in biomes 
4. join join join

In [8]:
df_feature_imp = pd.read_csv("/Users/varadakhot/Library/CloudStorage/OneDrive-Friedrich-Schiller-UniversitätJena/MCP_struct/RF_models_automation/RF_results/Rep_Seq_Position_Mapping/example_cluster_0_1_mixed/new_model/cluster_0_1_mixed_MSTA_aa_plus_ec6098re_EC6098_reference_feature_importance.tsv",
                             sep='\t',usecols=["index","gini_imp","msa_position"])
df_feature_imp
df_feature_imp = df_feature_imp.sort_values('gini_imp', ascending=False).drop_duplicates('msa_position',keep='first').reset_index().reset_index(names="feat_rank")
df_feature_imp

# NOTE: Because it is only based on positions and not pos+AA, we sort by the highest scoring pos+AA for each position (e.g. between 80_S and 80_P, choose highest ranking) and drop duplicates

df_feature_imp = df_feature_imp.sort_values('gini_imp', ascending=False)

# df_feature_imp = df_feature_imp.loc[df_feature_imp['feat_rank'] < 1000]
df_feature_imp

     feat_rank  level_0  index  gini_imp  msa_position
0            0        0  435_W  0.010456           435
1            1        1  330_K  0.009997           330
2            2        2   80_P  0.009928            80
3            3        4  324_Q  0.009069           324
4            4        5  445_F  0.008860           445
..         ...      ...    ...       ...           ...
561        561     2477  203_P  0.000054           203
562        562     2641   55_P  0.000050            55
563        563     2656  412_H  0.000049           412
564        564     2695  442_E  0.000048           442
565        565     5295  411_E  0.000007           411

[566 rows x 5 columns]

In [ ]:
df_surfaces = pd.read_csv("surface_area_A53.txt", skiprows=[0,1,2],sep="\t|:", names=["chain","position", "surface_area"])
df_surfaces

/var/folders/6c/dkl_rmf913l9h4s3pys_spm80000gn/T/ipykernel_48479/3962250446.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_surfaces = pd.read_csv("surface_area_A53.txt", skiprows=[0,1,2],sep="\t|:", names=["chain","position", "surface_area"])

                   chain  position  surface_area
0    #2//chain_id='A-53'         4    117.855551
1    #2//chain_id='A-53'         5     25.047236
2    #2//chain_id='A-53'         6    209.909256
3    #2//chain_id='A-53'         7    126.027098
4    #2//chain_id='A-53'         8      6.739850
..                   ...       ...           ...
470  #2//chain_id='A-53'       562     47.255225
471  #2//chain_id='A-53'       563      5.316433
472  #2//chain_id='A-53'       564      3.303428
473  #2//chain_id='A-53'       565     27.835667
474  #2//chain_id='A-53'       566     58.718364

[475 rows x 3 columns]